version: "2.3"
services:
  
  backend:
    build: ./backend/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    restart: always
    env_file:
      - backend/.env
    volumes:
      - ./backend:/backend
    networks:
      - local_network


networks:
  local_network:
    driver: bridge